Bump version to 5.0.0-dev
edgedb/edgedb-cli pull request #1301
Opened 2024-04-23 17:05 UTC by quinchs

2024-04-23 17:06 UTC, aljazerzen approved these changes

2024-04-23 17:18 UTC, elprans commented on Cargo.toml
> +version = "5.0.0-dev"
Shouldn't this be 5.1.0-dev?

2024-04-23 17:18 UTC, elprans requested changes
`5.1.0-dev` is the correct bump for `master` since `5.0.0` has been released already.

2024-04-25 18:03 UTC, elprans approved these changes

2024-04-25 18:03 UTC, merged