Use edgedb-tokio for talking to server
edgedb/edgedb-cli pull request #924
Opened 2023-01-23 09:37 UTC by tailhook

2023-01-23 09:41 UTC, tailhook commented
@fantix, might be quite a big change to review in one chunk. But, please, take a closer look to cloud stuff. And please try running it if you can, because currently its untested mostly.

2023-01-23 23:30 UTC, fantix requested changes
Some cloud operations are crashing because of creating runtime twice in some places, please see inline.

2023-01-23 23:30 UTC, fantix commented on src/portable/create.rs
> +async fn ask_name(
I think this function doesn't have to be async now.

2023-01-23 23:30 UTC, fantix commented on src/portable/project.rs
> +async fn ask_existing_instance_name(
Ditto, async not needed.

2023-01-23 23:30 UTC, fantix commented on src/portable/project.rs
> +async fn ask_name(
Ditto, async not required.

2023-02-02 23:33 UTC, fantix approved these changes

2023-02-07 16:07 UTC, merged